# Generated by Django 3.1.4 on 2021-02-04 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
