# Generated by Django 3.1.4 on 2021-02-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20210220_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='most_recent_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
